version: "3.8"
services:
  apache:
    container_name: Apache
    image: ub-apache
    build: 
      context: ${DIR_DFILES}/ubuntu/apache
      dockerfile: ./ub-apache-dockerfile
      args: 
       - DIR_DFILES=${DIR_DFILES}
       - TZ=${TZ}
       - A_PORT=${A_PORT}
    env_file: 
      - ./.env
    ports: 
      - ${A_PORT}:80
    networks: 
      net_apache:
          ipv4_address: 172.130.10.2
networks: 
  net_apache:
      ipam: 
          driver: default
          config: 
              - subnet: 172.130.10.0/24