version: "3"
services:
  node-nginx-nest:
    container_name: Node-nginx-nest
    image: ub-node-nginx-nest
    build: 
      context: ${DIR_DFILES}/ubuntu/node-nginx-nest
      dockerfile: ./ub-node-nginx-nest-dockerfile
      args: 
       - USUARIO=${USUARIO}
       - TZ=${TZ}
       - PASSWD=${PASSWD}
       - REPO_GITHUB=${REPO_GITHUB}
       - URL_GITHUB=${URL_GITHUB}
       - DB_HOST=${DB_HOST}
       - DB_NAME=${DB_NAME}
       - DB_USERNAME=${DB_USERNAME}
       - DB_PASSWORD=${DB_PASSWORD}
       - DB_PORT=${DB_PORT}
       - PORT=${PORT}
       - HOST_API=${HOST_API}
       - JWT_SECRET=${JWT_SECRET}
    env_file: 
      - ./.env
    ports: 
      - ${NNN_PORT}:3000
    networks: 
      net_node-nginx-nest:
          ipv4_address: 172.20.0.7
networks: 
  net_node-nginx-nest:
      ipam: 
          driver: default
          config: 
              - subnet: 172.20.0.0/16